### ISSUE TITLE
Book requires Java

### ISSUE THREAD

**Issue by tsalo** [NBCLab/nimare-paper#18]
In order to use MALLET, the book will need access to Java. Not sure how Neurolibre handles Docker images and if I need to provide one with both miniconda and java.

**Comment by tsalo** [comment]
@ltetrel, the failure noted in https://github.com/neurolibre/neurolibre-reviews/issues/7#issuecomment-1006909221 for annotation.md is:

```Text
[0;32m/srv/conda/envs/notebook/lib/python3.7/site-packages/nimare/utils.py[0m in [0;36mrun_shell_command[0;34m(command, env)[0m
[1;32m    961[0m     [0;32mif[0m [0mprocess[0m[0;34m.[0m[0mreturncode[0m [0;34m!=[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    962[0m         [0mstderr_line[0m [0;34m=[0m [0mstr[0m[0;34m([0m[0mprocess[0m[0;34m.[0m[0mstderr[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m,[0m [0;34m"utf-8"[0m[0;34m)[0m[0;34m[[0m[0;34m:[0m[0;34m-[0m[0;36m1[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 963[0;31m         [0;32mraise[0m [0mException[0m[0;34m([0m[0;34mf"Non zero return code: {process.returncode}\n{command}\n\n{stderr_line}"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mException[0m: Non zero return code: 127
/home/jovyan/.nimare/mallet/bin/mallet import-dir --input /home/jovyan/.nimare/mallet_model/texts --output /home/jovyan/.nimare/mallet_model/topic-input.mallet --keep-sequence --remove-stopwords

/home/jovyan/.nimare/mallet/bin/mallet: line 61: java: command not found
Exception: Non zero return code: 127
/home/jovyan/.nimare/mallet/bin/mallet import-dir --input /home/jovyan/.nimare/mallet_model/texts --output /home/jovyan/.nimare/mallet_model/topic-input.mallet --keep-sequence --remove-stopwords

/home/jovyan/.nimare/mallet/bin/mallet: line 61: java: command not found
```

It looks like there's no access to Java during the book build on Neurolibre's server.

**Comment by ltetrel** [comment]
On your system I assume it was installed locally right ? I have no idea how to install java on a docker :/ maybe it would be easier to change the sumission so it is not dependend on java ?

**Comment by tsalo** [comment]
I am actually in the process of replacing the class that uses Java with one that just uses scikit-learn to do the same thing, but that will mean pinning the book to a new NiMARE release. I think it's probably worth doing, but I'll need a couple of days to update the code in the book, as well as the data, to match the new release.

**Comment by tsalo** [comment]
I'm still debugging the new version, but it no longer requires Java so I'll close this issue.
