### ISSUE TITLE
Procedure for submission to NeuroLibre for technical review

### ISSUE THREAD

**Issue by tsalo** [NBCLab/nimare-paper#21]
Here I will document the submission steps I take as I go through them.

1. I created a JupyterBook based on the tutorial at https://jupyterbook.org/start/your-first-book.html.
    - The book config was originally at the top level of the repo, instead of within `content`. That seems to be the default for JupyterBook, but doesn't work for NeuroLibre.
2. I reorganized the book according to NeuroLibre's instructions (https://docs.neurolibre.org/en/latest/SUBMIT.html#preprint-repository-structure) around 4bd027eec00e81b8c9242119a386ecd9393d3148.
    - This meant removing all of my data files from the GitHub repository, uploading them to the OSF (I used the Google Drive OSF interface because uploading folders to Google Drive is _much_ easier than uploading them directly to the OSF), and having git ignore the data folder so that I could retain local copies for the data in order to build the book locally. It also meant creating a binder folder with the settings for grabbing the OSF files.
    - This also involved creating paper.bib and paper.md files, which contain the bibliography and some metadata for the book.
3. Given the computational and time requirements for building the book, my general workflow was to write most code on my laptop, push to GitHub, pull to the FIU HPC, submit the job (requiring the FIU HPC-specific files in the fiu-hpc folder), push the built book back to GitHub, pull to my laptop, review, revise, push again, etc. Probably would have been simpler to set up a reasonable editor on the HPC, but in any case the `fiu-hpc/` files would have been necessary.
    - Processing nodes on the FIU HPC do not have internet access, so I had to download all relevant data files separately.  Neurolibre also doesn't store generated files for long (see #12), so I had to save those and upload them to the OSF before submitting to Neurolibre as well.
    - Given the lack of internet access, I haven't actually tested [NeuroLibre's `repo2data` instructions](https://docs.neurolibre.org/en/latest/SUBMIT.html#testing-book-build-locally) on the HPC.
4. Submitted to RoboNeuro preprint builder. It successfully built, but my data_requirement file and data directory path in my content files did not match up. Attempted to fix this in ddb4b02.
    - However, one thing I'm worried about is that locally testing `repo2data` downloaded the files to `binder/data/` instead of `data/`. I'm hoping that won't be an issue in the actual build, since the setup I have here is the same as the one in https://github.com/neurostuff/ohbm2021-nimare-tutorial, and that one had the data folder outside of the binder folder.
5. I opened an issue in this repository (#22) and tagged one of the NeuroLibre admins (Loic Tetrel), who recommended that I open an issue in the `neurolibre-binderhub` repo. It turned out that `repo2data` needed to be updated on their end, so he did that and I resubmitted. The new submission failed without a meaningful error message and with no log sent to my email. I mentioned this in the issue and Loic recommended that I open an issue in the `roboneuro` repo about that element.
6. Part of the problem seems to be that the book was hitting RoboNeuro/NeuroLibre's time limits. The service is not designed for books that take so long to build. Loic recommended using the jupyter cache instead. I changed to using the cache and re-built on the HPC, then resubmitted to RoboNeuro.
    - It failed with the errors `{}`.
    - The issue here was that the specified cache location was not where the cache was. I had to fix the path in the config file, and afterwards the RoboNeuro build worked.
7. Submitted to NeuroLibre on 11/15/2021.
8. Pre-review issue opened on 11/30/2021: https://github.com/neurolibre/neurolibre-reviews/issues/6.
    - The book was not building easily. Some issues on NeuroLibre's side, I believe, but also the book's build time is still way too long (~8 hours), though we're caching to avoid actually building the book.
9. Review issue opened on 12/6/2021: https://github.com/neurolibre/neurolibre-reviews/issues/7.
    - The book was using too much memory for NeuroLibre's server (see #25). Including a memory limit on the initial SLURM jobs to match NeuroLibre's restrictions would have made things much easier, I think.
    - Restricting the memory in the FIU HPC SLURM job may have helped, but Pierre believes that there may be issues with memory usage spikes, _or_ perhaps that the NeuroLibre server's memory limit is stricter. In any case, I had to reduce the code's memory usage even after the HPC job succeeded.
10. Book successfully built on NeuroLibre on 2/16/2022.
    - Loic told me to directly test on the CONP Binder server. He created a mechanism for debugging that let me access the Binder server without building. I used that to build the book in a terminal on the server, which gave me much more informative error messages. I was able to identify the issue with SCALE and create a new release with a more efficient version of the SCALE algorithm, after which it built!
11. A link to the built book on their server was made available on 3/3/2022, but minting the DOI and pushing the preprint to the website takes a few additional weeks, so we ended up using the server link for our Aperture submission.

Major takeaways:

1. NeuroLibre's Jupyter book organization is slightly different from the standard one, but they do document it on the website. Perhaps they could emphasize the differences a bit more though?
2. The build server has specific limits on memory and duration, which I think could be documented. Maybe they could provide example SLURM and/or LSF jobs?
3. The preview service kind of just disappears after ~10 minutes, and never sends a followup email after that. Even when the build is still running. It just says that there's no preview for that build.
4. My particular workflow uses processing nodes _without_ internet access for development. This slowed debugging down quite a bit, and I don't know how common of a problem it is.
5. Debugging on the CONP Binder was a useful final step. It provided more informative error messages without relying on Loic to act as a messenger between me and the system.

**Comment by ltetrel** [comment]
This is something that is valuable for us, as this shows that the submission process can be quite heavy...
Also it shows how valuable an interactive preprint as us have much more value, than just a pdf :)

**Comment by tsalo** [comment]
Exactly! Angie asked me to keep notes on the submission for both the NeuroLibre technical review and the later Aperture content review.
