### ISSUE TITLE
RoboNeuro data downloading may be failing

### ISSUE THREAD

**Issue by tsalo** [NBCLab/nimare-paper#22]
I am planning to submit to NeuroLibre soon, and am working on the testing steps prior to submission. Calling `repo2data` locally works fine, but the data don't seem to download when I submit the repository to RoboNeuro. The NeuroLibre docs say to open an issue in my repo for a NeuroLibre admin to see. @ltetrel, is this something you'd be able to help with?

The dataset should be ~391MB, so I think it's within NeuroLibre's restrictions. It's stored on Google Drive, but I linked the Drive folder to an OSF repository so I could use `osfclient` for downloading.

**Comment by ltetrel** [comment]
Are you in the testing phase with the roboneuro page, or you already make a submission (in that case there should be an issue for your submission on https://github.com/neurolibre/neurolibre-reviews/issues) ?

**Comment by tsalo** [comment]
I'm just on the testing phase with the roboneuro page right now. I have been building the book on my university's HPC until now.

**Comment by ltetrel** [comment]
Ok you can create an issue here, and mention also that issue here for history:
https://github.com/neurolibre/neurolibre-binderhub

**Comment by tsalo** [comment]
I've opened https://github.com/neurolibre/neurolibre-binderhub/issues/33. Thanks!
