### ISSUE TITLE
Run memory profiler on notebooks

### ISSUE THREAD

**Issue by tsalo** [NBCLab/nimare-paper#25]
I have drafted a script to do this ([`profile_book.py`](https://github.com/NBCLab/nimare-paper/blob/master/fiu-hpc/profile_book.py)), but I can't get it to work. The problem seems to be that, when I use the script, regardless of what I do, Repo2Data cannot find the existing data and tries to download it. That obviously doesn't work on a processing node on the FIU HPC (which is the only place I can run this), since they don't have internet access. I assume that something about running the notebooks directly is causing the working directory to be someplace other than where it is normally, but I've tried setting that working directory a few different ways and I just don't know why it's still a problem.

**Comment by tsalo** [comment]
I think the problem was unrelated to the path. Namely, I had updated the data requirements file at one point but failed to update the data folder on the HPC, so Repo2Data detected the update and tried to download the new data files.

**Comment by tsalo** [comment]
@ltetrel I just wanted to tag you in this. I figured it might be a good idea to work on the benchmarking problem in a separate issue rather than cluttering up https://github.com/neurolibre/neurolibre-reviews/issues/7. The job is currently running, so I should be able to share the results tomorrow. I _am_ worried that `memory_profiler`'s `memory_usage` is not doing what I expected, but I can follow up about that tomorrow if I'm right.

**Comment by ltetrel** [comment]
Alright we will look into that.
For now what I can say is that it seems to fail when calling the `fit` function (ex `meta_amyg.fit(dset_amygdala)` for `mcma.md` and `sub_meta.fit(sleuth_dset1, sleuth_dset2)` in `substraction.md`). What I suspect here is that you are benchmarking the average memory, and not the spike memory (what could cause issue on neurolibre).

An interresting experiment would be to restrict the memory usage also on your HPC? I will look into your benchmarking code tomorrow.

**Comment by ltetrel** [comment]
Your HPC mostly have job history information, so you should be able to check its memory consumption. For example if it using slurm, you can check minimum memory requirement for a finished job with:
`sacct -j jobid --format=User,JobID,Jobname,time,start,end,MaxRss,ReqMem`

**Comment by tsalo** [comment]
>An interesting experiment would be to restrict the memory usage also on your HPC?

That's a great suggestion. I've limited the job to 4GB.

>For now what I can say is that it seems to fail when calling the fit function (ex meta_amyg.fit(dset_amygdala) for mcma.md and sub_meta.fit(sleuth_dset1, sleuth_dset2) in substraction.md).

I've reduced the number of studies in the amygdala MACM from ~1300 to 500, and have reduced the number of iterations for the subtraction analysis from 10000 to 1000, so hopefully that will fix that issue. I'm re-running the job now.

>What I suspect here is that you are benchmarking the average memory, and not the spike memory (what could cause issue on neurolibre).

I was trying to measure memory usage every 0.5 seconds, but who knows if I was doing it correctly. I think limiting the memory might be the easier approach, so that's what I'm trying out now.

>For example if it using slurm, you can check minimum memory requirement ReqMem for a finished job with:
sacct -j jobid --format=User,JobID,Jobname,time,start,end,MaxRss,ReqMem

It looks like the profiling job was using 6GB. I'm not sure what the build is taking, but I assume it's in that area. Hopefully the new changes will reduce that substantially.

**Comment by ltetrel** [comment]
> It looks like the profiling job was using 6GB. I'm not sure what the build is taking, but I assume it's in that area. Hopefully the new changes will reduce that substantially.

Indeed it is very possible that a jupyter-book execution takes more memory than a pure notebook execution. So maybe restrict to 3.5G just to have little room, but let's try that if your on-going experiment is not working.

**Comment by tsalo** [comment]
The job I ran was just to build the book with a memory limit, but no memory profiling. With the updates to the MACM and subtraction analyses pages, it built successfully with a max of 4GB.

**Comment by ltetrel** [comment]
Ok, and `resources.md` ?

**Comment by tsalo** [comment]
I didn't make any changes to `resources.md`, but it still built successfully... Is it possible that there's an issue with [my SLURM submission script](https://github.com/NBCLab/nimare-paper/blob/1e82241c21e5640f42a2cc18b03662bd97c13fec/fiu-hpc/build_book.sbatch)? Sorry for the confusion.

**Comment by ltetrel** [comment]
Looking at it seems to be okay :+1:

**Comment by tsalo** [comment]
Just to be sure I ran the build on our default partition as well, after cleaning out the HTML files. It looks like it used 4 GB split across the job and its "batch" 😕. In any case, I don't think memory went beyond the limit at any point, so I think it should be good to go on NeuroLibre's server now, unless there's something I'm missing with `resources.md`.

```bash
sacct -j 5380312 --format=User,JobID,Jobname,time,start,end,MaxRss,ReqMem
```
```Text
     User        JobID    JobName  Timelimit               Start                 End     MaxRSS     ReqMem 
--------- ------------ ---------- ---------- ------------------- ------------------- ---------- ---------- 
 tsalo006 5380312      nimare-pa+  UNLIMITED 2022-01-05T14:56:35 2022-01-05T16:27:20                2000Mc 
          5380312.bat+      batch            2022-01-05T14:56:35 2022-01-05T16:27:20    125336K     2000Mc 
```

**Comment by ltetrel** [comment]
Ok let's try this!

**Comment by tsalo** [comment]
Given that it runs under the requested memory limit, I'm going to close this issue.
